#!/usr/bin/env bash
set -euo pipefail

# install-xen-orchestra.sh
# Minimal automated installer for Xen Orchestra (from sources) on Ubuntu 24.04
# - installs OS packages, Node.js (latest LTS), enables Yarn via corepack
# - installs Redis, clones xen-orchestra, builds it
# - generates a self-signed certificate and writes /etc/xo-server/config.toml
# - opens ports 80 and 443 via UFW and installs a systemd service for xo-server
#
# Usage: sudo ./install-xen-orchestra.sh [--dir /opt/xen-orchestra] [--domain example.com]

XO_DIR="/opt/xen-orchestra"
DOMAIN="$(hostname -f || echo localhost)"

while [[ $# -gt 0 ]]; do
	case $1 in
		--dir)
			XO_DIR="$2"; shift 2;;
		--domain)
			DOMAIN="$2"; shift 2;;
		-h|--help)
			echo "Usage: sudo $0 [--dir /opt/xen-orchestra] [--domain example.com]"; exit 0;;
		*) echo "Unknown arg: $1"; exit 1;;
	esac
done

if [[ $(id -u) -ne 0 ]]; then
	echo "This script must be run as root (sudo)." >&2
	exit 1
fi

echo "Installing Xen Orchestra from sources into: $XO_DIR"
echo "Using domain/hostname: $DOMAIN"

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get install -y --no-install-recommends \
	ca-certificates curl wget gnupg lsb-release software-properties-common \
	build-essential redis-server libpng-dev git python3-minimal libvhdi-utils \
	lvm2 cifs-utils nfs-common ntfs-3g openssl ufw

# Ensure Redis is enabled and running
systemctl enable --now redis-server
sleep 2
if ! command -v redis-cli >/dev/null; then
	echo "redis-cli not found; please check redis installation." >&2
fi

echo "Installing Node.js (Node 20.x LTS) via NodeSource"
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs

echo "Enabling corepack and preparing yarn"
if command -v corepack >/dev/null; then
	corepack enable
	corepack prepare yarn@stable --activate
else
	npm install -g yarn
fi

echo "Creating user and directories"
mkdir -p "$XO_DIR"
chown -R root:root "$XO_DIR"

echo "Cloning xen-orchestra repository"
if [[ -d "$XO_DIR/.git" ]]; then
	echo "Repository already present in $XO_DIR, pulling latest." 
	git -C "$XO_DIR" fetch --all
	git -C "$XO_DIR" checkout -q master || true
	git -C "$XO_DIR" pull --ff-only || true
else
	git clone -b master https://github.com/vatesfr/xen-orchestra "$XO_DIR"
fi

echo "Installing yarn dependencies and building xen-orchestra"
cd "$XO_DIR"
yarn --network-concurrency 1
yarn build

# Create SSL directory
SSL_DIR="/etc/xo-server/ssl"
mkdir -p "$SSL_DIR"

CERT_FILE="$SSL_DIR/cert.pem"
KEY_FILE="$SSL_DIR/key.pem"

if [[ -f "$CERT_FILE" && -f "$KEY_FILE" ]]; then
	echo "Certificate and key already exist, skipping generation."
else
	echo "Generating self-signed certificate for $DOMAIN"
	openssl req -x509 -nodes -days 3650 -newkey rsa:4096 \
		-keyout "$KEY_FILE" -out "$CERT_FILE" \
		-subj "/CN=$DOMAIN" -addext "subjectAltName=DNS:$DOMAIN,IP:127.0.0.1"
	chmod 644 "$CERT_FILE"
	chmod 600 "$KEY_FILE"
fi

echo "Writing XO server configuration to /etc/xo-server/config.toml"
mkdir -p /etc/xo-server
cat > /etc/xo-server/config.toml <<EOF
# Generated by install-xen-orchestra.sh
[http]
redirectToHttps = true

[[http.listen]]
hostname = '0.0.0.0'
port = 80

[[http.listen]]
hostname = '0.0.0.0'
port = 443
# Let autoCert be false since we provide our own cert
autoCert = false
cert = '$CERT_FILE'
key = '$KEY_FILE'

# Public URL (optional)
publicUrl = 'https://$DOMAIN'

[redis]
uri = 'redis://localhost:6379/0'

EOF

echo "Config file written."

echo "Configuring UFW to allow ports 80 and 443"
if command -v ufw >/dev/null; then
	ufw allow 22/tcp || true
	ufw allow 80/tcp || true
	ufw allow 443/tcp || true
	# enable UFW if inactive
	if ufw status | grep -q "Status: inactive"; then
		ufw --force enable
	fi
else
	echo "ufw not installed, skipping firewall setup." >&2
fi

echo "Creating systemd service for xo-server"
SERVICE_FILE="/etc/systemd/system/xo-server.service"
cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=XO Server
After=network-online.target redis.service

[Service]
Type=simple
Environment="DEBUG=xo:main"
WorkingDirectory=$XO_DIR/packages/xo-server
ExecStart=/usr/bin/node $XO_DIR/packages/xo-server/dist/cli.mjs
Restart=always
SyslogIdentifier=xo-server

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now xo-server || true

echo "Waiting a few seconds for XO to start..."
sleep 5

echo "Basic checks:" 
echo " - Redis ping: "; redis-cli ping || true
ss -tlnp | grep -E ':80|:443' || true

cat <<FINISH
Installation finished.

- Xen Orchestra installed at: $XO_DIR
- XO config: /etc/xo-server/config.toml
- SSL cert: $CERT_FILE
- SSL key: $KEY_FILE
- Systemd service: $SERVICE_FILE

Visit https://$DOMAIN/ (accept the self-signed certificate in your browser).

Notes:
- This script runs XO as root (systemd ExecStart using root). For improved
	security, create a dedicated user and adapt the service file & ownership.
- To run XO under a non-privileged user keep http ports >1024 or use a
	reverse-proxy (nginx) to terminate TLS.
FINISH

# Mark todo items as completed (local record only)
exit 0
