FROM rockylinux:9
RUN dnf install -y epel-release \
    && dnf install -y sudo git bash bats ShellCheck ca-certificates \
    && dnf clean all \
    && ln -s /usr/bin/ShellCheck /usr/local/bin/shellcheck

# Create non-root user with passwordless sudo
RUN useradd -m -s /bin/bash tester \
    && echo "tester ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER tester
WORKDIR /home/tester

COPY --chown=tester:tester . /home/tester/install-xen-orchestra/

WORKDIR /home/tester/install-xen-orchestra

CMD ["bats", "tests/integration/test_install_smoke.bats"]
